### PR TITLE
Release 1.7.0

### PR DESCRIPTION
**Pull request by thc202**
Update version, readme, and changelog for new release.

### CODE REVIEW

**Comment by kingthorin** [comment]
Are we concerned about either of those LGTM issues?

**Comment by thc202** [comment]
They are being fixed (they already were in develop).

**Comment by kingthorin** [comment]
So I should wait for further changes or that's a future thing and this is good to go as-is?

**Comment by thc202** [comment]
I meant they are being fixed with the changes being merged, so, good to go as is.

**Comment by kingthorin** [comment]
OMG I’m so used to it saying “introduces” that I didn’t actually read it.....yikes! Sorry

**Pull request merged**
