### PR TITLE
Normalise format/indentation of source code

### PR DESCRIPTION
**Pull request by thc202**
Set up the Spotless plugin to check/enforce the format/indentation of
the whole source code, currently set to use Google Java Style (AOSP).

### CODE REVIEW

**Comment by thc202** [comment]
It's split into two commit as it's easier to revert the changes ;)

**Comment by thc202** [comment]
To be clear, this pull request is for an initial review of the format/style.

**Comment by JordanGS** [comment]
I like this a lot.

Personally I do 4 spaces in java files and 2 in xml's for indentation.

Cheers, Goran.

**Comment by thc202** [comment]
@kingthorin
> Does this include line ending changes?

Yes, line wrapping and a lot more:
https://google.github.io/styleguide/javaguide.html

> Are we going to publish the Eclipse style config to the repos?

If we really need to, yes. If we used the default, then the config already exists and we could use just that, if we are going to change the format then we need tweak them and push to the repo.

> Are we going to prepare a blog post or wiki entry to go with all this (for core/extensions).

More a dev group post and update dev guidelines.

**Comment by rain0r** [comment]
This is a proposal. It's the [Google Style Guide](https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml) for Java, but with 4 spaces as a tab (instead of 2).
It can be imported in Eclipse.
https://gist.github.com/rain0r/3050b5eff38ef97e962921307d284eee

**Comment by thc202** [comment]
@rain0r that's not enough to produce the expected output, one also has to use [google-java-format](https://github.com/google/google-java-format), unless we don't care about that...

**Comment by rain0r** [comment]
@thc202 How do you mean that? For the style checks performed by CI?

**Comment by thc202** [comment]
No, the actual format applied to the code, specially line wrapping and also the position of some keywords.

**Comment by kingthorin** [comment]
@thc202 @psiinon I've looked through the formatted part again. I think I can get used to the double space (vs tab or 4/5 spaces). It isn't quite as obvious but it's fine. Plus if the style is enforced by the IDE/Plugin it's a no-brainer. I think I'm good with this...

I've read about 2/3 of the Google Java Style Guide and none of it seems too disruptive vs. what I'm (we're) used to with Eclipse defaults. I'll read the rest at lunch but so far no show stoppers from my point-of-view.

**Comment by thc202** [comment]
Rebased and changed to use AOSP variant, which uses 4 spaces instead of 2.

@kingthorin, @psiinon PTAL (again).

**Comment by thc202** [comment]
@psiinon looks good?

**Comment by psiinon** [comment]
Yep :)

**Comment by thc202** [comment]
Thanks!

**Pull request merged**
